[package]
name = "fast_qr"
version = "0.3.1"
authors = ["erwan.vivien <erwan.vivien@epita.fr>"]
edition = "2018"
description = "Generates optimized QRCode"
documentation = "https://docs.rs/fast_qr/latest/fast_qr/"
homepage = "https://doc.fast-qr.com/"
readme = "README.md"
repository = "https://github.com/erwanvivien/QR-Gen/"
keywords = ["qr", "qrcode", "qr-generator", "qrcode-generator",
            "qr-gen"]
categories = ["multimedia", "multimedia::encoding", "multimedia::images"]
exclude = ["/src/tests/", ".*"]
rust-version = "1.59"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
debug = true
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
