[package]
name = "qrgen"
version = "0.1.0"
authors = ["erwan.vivien <erwan.vivien@epita.fr>"]
edition = "2018"
description = "Generates QRCode for any type of data"
readme = "README.md"
repository = "https://github.com/erwanvivien/QR-Gen/"
keywords = ["qr", "qrcode", "qr generator", "qrcode generator",
            "qrgen"]
categories = ["multimedia", "multimedia::encoding", "multimedia::images"]
exclude = ["/src/tests/", ".*"]
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
debug = true
