[package]
name = "fast-qr"
version = "0.2.0"
authors = ["erwan.vivien <erwan.vivien@epita.fr>"]
edition = "2018"
description = "Generates optimized QRCode"
readme = "README.md"
repository = "https://github.com/erwanvivien/QR-Gen/"
keywords = ["qr", "qrcode", "qr-generator", "qrcode-generator",
            "qrgen"]
categories = ["multimedia", "multimedia::encoding", "multimedia::images"]
exclude = ["/src/tests/", ".*"]
rust-version = "1.59"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
debug = true
