[package]
name = "qrgen"
version = "0.1.0"
authors = ["erwan.vivien <erwan.vivien@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
parking_lot = "0.11.1"